CREATE TABLE IF NOT EXISTS User (
id INTEGER PRIMARY KEY AUTOINCREMENT,
position TEXT DEFAULT '',
login TEXT DEFAULT '',
password TEXT DEFAULT '',
power_level INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Projects (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT DEFAULT '',
description TEXT DEFAULT '',
start_date TEXT DEFAULT '',
end_date TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS Clients (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT DEFAULT '',
contact TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS Employees (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT DEFAULT '',
position TEXT DEFAULT '',
contact TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS Materials (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT DEFAULT '',
quantity INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Tasks (
id INTEGER PRIMARY KEY AUTOINCREMENT,
project_id INTEGER DEFAULT 0,
employee_id INTEGER DEFAULT 0,
description TEXT DEFAULT '',
status TEXT DEFAULT '',
FOREIGN KEY (project_id) REFERENCES Projects (id),
FOREIGN KEY (employee_id) REFERENCES Employees (id)
);